version: '2'
volumes:
  database_data:
    driver: local
services:
  api:
    build: .
    ports:
      - "5000:5000"
  db:
    image: postgres:9.6.1
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data
