export const ILLUSTRATION_URLS = {
  asking: 'https://s3.amazonaws.com/youmustfight_kit/assets/conversation/asking.png',
  business: 'https://s3.amazonaws.com/youmustfight_kit/assets/conversation/business.png',
  help: 'https://s3.amazonaws.com/youmustfight_kit/assets/conversation/help.png',
  navigating: 'https://s3.amazonaws.com/youmustfight_kit/assets/conversation/navigating.png',
  renters: 'https://s3.amazonaws.com/youmustfight_kit/assets/conversation/renters.png',
  report: 'https://s3.amazonaws.com/youmustfight_kit/assets/conversation/report.png',
  neighborhood: 'https://s3.amazonaws.com/youmustfight_kit/assets/conversation/residents.png',
  parents: 'https://s3.amazonaws.com/youmustfight_kit/assets/conversation/parents.png',
  sanitation: 'https://s3.amazonaws.com/youmustfight_kit/assets/conversation/sanitation.png',
  transit: 'https://s3.amazonaws.com/youmustfight_kit/assets/conversation/transit.png',
  voting: 'https://s3.amazonaws.com/youmustfight_kit/assets/conversation/voting.png',
  whatCanIAsk: 'https://s3.amazonaws.com/youmustfight_kit/assets/conversation/what-can-i-ask.png',
  hand: 'https://s3.amazonaws.com/youmustfight_kit/assets/conversation/hand.png',
  events: 'https://s3.amazonaws.com/youmustfight_kit/assets/conversation/events.png',
};
